export type ChannelKey = "wa" | "ig" | "tg" | "em";

export type TagColor = "amber" | "green" | "red" | "blue" | "purple" | "pink" | "neutral";

export type ConversationMock = {
  id: number;
  name: string;
  ch: ChannelKey;
  chLabel: string;
  col: string;
  init: string;
  avaBg: string;
  prev: string;
  time: string;
  unread: number;
  tags: { label: string; color: TagColor }[];
  lastBy: "user" | "ai" | "human";
  online: boolean;
  phone: string;
  email: string;
  city: string;
  customer: string;
  orders: number;
  labels: string[];
  needsHuman: boolean;
};

export const CONVERSATIONS: ConversationMock[] = [
  {
    id: 1,
    name: "Laura González",
    ch: "wa",
    chLabel: "WhatsApp",
    col: "#25d366",
    init: "LG",
    avaBg: "linear-gradient(135deg,#25d366,#0e8c48)",
    prev: "¿Envían a Monterrey? Urgente para el viernes",
    time: "2m",
    unread: 2,
    tags: [{ label: "Lead caliente", color: "red" }],
    lastBy: "user",
    online: true,
    phone: "+52 81 2345 6789",
    email: "laura.g@mail.com",
    city: "Monterrey, MX",
    customer: "Nuevo",
    orders: 0,
    labels: ["lead", "whatsapp"],
    needsHuman: false,
  },
  {
    id: 2,
    name: "@mariana.d",
    ch: "ig",
    chLabel: "Instagram",
    col: "#e1306c",
    init: "M",
    avaBg: "linear-gradient(135deg,#e1306c,#833ab4)",
    prev: "¿Tienes la talla M disponible?",
    time: "5m",
    unread: 1,
    tags: [{ label: "Pre-venta", color: "amber" }],
    lastBy: "user",
    online: true,
    phone: "—",
    email: "mariana.dg@ig.com",
    city: "CDMX, MX",
    customer: "Recurrente",
    orders: 3,
    labels: ["catalog"],
    needsHuman: false,
  },
  {
    id: 3,
    name: "Carlos Rivera",
    ch: "tg",
    chLabel: "Telegram",
    col: "#29b6f6",
    init: "CR",
    avaBg: "linear-gradient(135deg,#29b6f6,#0288d1)",
    prev: "Tengo problema con mi pedido #4521, necesito hablar con alguien",
    time: "12m",
    unread: 3,
    tags: [
      { label: "Soporte", color: "blue" },
      { label: "Necesita humano", color: "red" },
    ],
    lastBy: "user",
    online: false,
    phone: "+52 33 1122 3344",
    email: "crivera@mail.com",
    city: "Guadalajara, MX",
    customer: "Recurrente",
    orders: 7,
    labels: ["support", "vip"],
    needsHuman: true,
  },
  {
    id: 4,
    name: "ana@acme.co",
    ch: "em",
    chLabel: "Email",
    col: "#a78bfa",
    init: "A",
    avaBg: "linear-gradient(135deg,#a78bfa,#6d28d9)",
    prev: "Propuesta para 50 unidades — empresa Acme",
    time: "1h",
    unread: 0,
    tags: [{ label: "B2B", color: "purple" }],
    lastBy: "ai",
    online: false,
    phone: "—",
    email: "ana@acme.co",
    city: "Querétaro, MX",
    customer: "Empresa",
    orders: 0,
    labels: ["b2b", "proposal"],
    needsHuman: false,
  },
  {
    id: 5,
    name: "Jorge Luna",
    ch: "wa",
    chLabel: "WhatsApp",
    col: "#25d366",
    init: "JL",
    avaBg: "linear-gradient(135deg,#10b981,#047857)",
    prev: "Cotizar 10 unidades modelo X-200",
    time: "2h",
    unread: 0,
    tags: [{ label: "Cotización", color: "amber" }],
    lastBy: "ai",
    online: false,
    phone: "+52 55 9988 7766",
    email: "jluna@mail.com",
    city: "Puebla, MX",
    customer: "Recurrente",
    orders: 2,
    labels: ["quote"],
    needsHuman: false,
  },
  {
    id: 6,
    name: "@foodielover.mx",
    ch: "ig",
    chLabel: "Instagram",
    col: "#e1306c",
    init: "F",
    avaBg: "linear-gradient(135deg,#ec4899,#be185d)",
    prev: "¿Qué horario tienen hoy?",
    time: "3h",
    unread: 0,
    tags: [],
    lastBy: "ai",
    online: false,
    phone: "—",
    email: "—",
    city: "CDMX, MX",
    customer: "Nuevo",
    orders: 0,
    labels: ["faq"],
    needsHuman: false,
  },
  {
    id: 7,
    name: "soporte@shop.io",
    ch: "em",
    chLabel: "Email",
    col: "#a78bfa",
    init: "S",
    avaBg: "linear-gradient(135deg,#8b5cf6,#6366f1)",
    prev: "Re: Devolución orden #9821",
    time: "5h",
    unread: 0,
    tags: [{ label: "Resuelto", color: "green" }],
    lastBy: "human",
    online: false,
    phone: "—",
    email: "soporte@shop.io",
    city: "—",
    customer: "Recurrente",
    orders: 5,
    labels: ["support"],
    needsHuman: false,
  },
  {
    id: 8,
    name: "Diego M.",
    ch: "wa",
    chLabel: "WhatsApp",
    col: "#25d366",
    init: "DM",
    avaBg: "linear-gradient(135deg,#22c55e,#15803d)",
    prev: "Perfecto, mañana paso por él. Gracias!",
    time: "1d",
    unread: 0,
    tags: [{ label: "Resuelto", color: "green" }],
    lastBy: "user",
    online: false,
    phone: "+52 81 5544 3322",
    email: "diegom@mail.com",
    city: "Monterrey, MX",
    customer: "Recurrente",
    orders: 4,
    labels: ["pickup"],
    needsHuman: false,
  },
  {
    id: 9,
    name: "Patricia S.",
    ch: "wa",
    chLabel: "WhatsApp",
    col: "#25d366",
    init: "PS",
    avaBg: "linear-gradient(135deg,#059669,#064e3b)",
    prev: "¿Sigue vigente la promo del 20%?",
    time: "1d",
    unread: 0,
    tags: [],
    lastBy: "ai",
    online: false,
    phone: "+52 55 2211 8877",
    email: "psanchez@mail.com",
    city: "CDMX, MX",
    customer: "Nuevo",
    orders: 0,
    labels: ["promo"],
    needsHuman: false,
  },
  {
    id: 10,
    name: "@traveler_co",
    ch: "ig",
    chLabel: "Instagram",
    col: "#e1306c",
    init: "T",
    avaBg: "linear-gradient(135deg,#f43f5e,#9f1239)",
    prev: "Amazing product! Quick question about shipping to USA",
    time: "2d",
    unread: 0,
    tags: [{ label: "Internacional", color: "blue" }],
    lastBy: "ai",
    online: false,
    phone: "—",
    email: "hello@traveler.co",
    city: "Miami, US",
    customer: "Nuevo",
    orders: 0,
    labels: ["international"],
    needsHuman: false,
  },
];

export type ThreadItem =
  | { type: "day"; at: string }
  | { type: "handoff"; text: string; time: string }
  | { type?: undefined; from: "user" | "ai" | "human"; text: string; time: string };

export const THREAD_LAURA: ThreadItem[] = [
  { type: "day", at: "Ayer" },
  { from: "user", text: "Hola! Quisiera saber si envían a Monterrey", time: "10:42" },
  { from: "user", text: "Es para un regalo", time: "10:42" },
  {
    from: "ai",
    text: "¡Hola Laura! Sí, tenemos envíos a todo Monterrey en 24–48h. El costo es $89 MXN y es gratis en compras mayores a $1,500.",
    time: "10:43",
  },
  { from: "user", text: "Perfecto. ¿Puedo pagar con transferencia?", time: "10:45" },
  {
    from: "ai",
    text: "Claro, aceptamos transferencia, tarjeta y OXXO. ¿Te paso los datos de la cuenta?",
    time: "10:45",
  },
  { type: "day", at: "Hoy" },
  { from: "user", text: "¿Envían a Monterrey? Urgente para el viernes", time: "14:02" },
  {
    from: "ai",
    text: "Sí Laura, si tu pedido se confirma hoy antes de las 18:00, llega el viernes. ¿Te ayudo a finalizar la orden?",
    time: "14:02",
  },
  {
    type: "handoff",
    text: "M2 detectó intención de compra alta — lead marcado como caliente",
    time: "14:03",
  },
  { from: "user", text: "Sí porfa! Son 3 del modelo X-200", time: "14:05" },
];
